// Python Frontend-D Vergin Jenifer/handson_7/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header(props) {

    const enrolledCourses = useSelector(
        state => state.enrollment.enrolledCourses
    );

    return (
        <header>
            <h1>{props.siteName}</h1>

            <p>
                Enrolled Courses: {enrolledCourses.length}
            </p>

            <nav>
                <Link to="/">Home</Link>
                <Link to="/courses">Courses</Link>
                <Link to="/profile">Profile</Link>
            </nav>
        </header>
    );
}

export default Header;

// Python Frontend-D Vergin Jenifer/handson_8/student-portal-vue/src/components/Header.vue
<template>
  <header>
    <h1>Student Portal</h1>

    <p>
      Enrolled Courses: {{ store.enrolledCourses.length }}
    </p>

    <nav>
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile</RouterLink>
    </nav>
  </header>
</template>

<script setup>
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<style scoped>

</style>
