// Python Frontend-D Vergin Jenifer/handson_8/student-portal-vue/src/components/Header.vue
<template>
  <header>
    <h1>Student Portal</h1>

    <p>
      Enrolled Courses: {{ store.enrolledCourses.length }}
    </p>

    <nav>
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile</RouterLink>
    </nav>
  </header>
</template>

<script setup>
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<style scoped>

</style>

// Python Frontend-D Vergin Jenifer/handson_5/src/components/Header.jsx
function Header(props) {
    return (
        <header>
            <h1>{props.siteName}</h1>
            <p>Enrolled Courses: {props.enrolledCount}</p>
            <nav>
                <a href="#">Home</a>
                <a href="#">Courses</a>
                <a href="#">Profile</a>
            </nav>
        </header>
    );
}

export default Header;
